import {
  BiLogoJavascript,
  BiLogoTypescript,
  BiLogoReact,
  BiLogoVuejs,
  BiLogoRedux,
  BiLogoMongodb,
  BiLogoPostgresql,
  BiLogoDocker,
  BiLogoGithub,
  BiLogoGitlab,
  BiLogoFigma,
  BiLogoGraphql,
  BiLogoHtml5,
  BiLogoCss3,
} from 'react-icons/bi';
import {
  SiExpress,
  SiNextdotjs,
  SiNestjs,
  SiJest,
  SiCypress,
  SiMui,
  SiEslint,
  SiPostcss,
  SiWebpack,
  SiSwagger,
  SiSequelize,
  SiMongoose,
  SiAxios,
  SiTailwindcss,
  SiBem,
  SiAntdesign,
  SiMocha,
  SiHandlebarsdotjs,
  SiSvg,
  SiForgejo,
  SiSharp,
} from 'react-icons/si';

export const tagsDict: Record<string, { label: string, icon?: any }> = {
  tagJavaScript: { label: 'JavaScript', icon: BiLogoJavascript },
  tagTypeScript: { label: 'TypeScript', icon: BiLogoTypescript },
  tagReact: { label: 'React.js', icon: BiLogoReact },
  tagRedux: { label: 'Redux', icon: BiLogoRedux },
  tagExpress: { label: 'Express.js', icon: SiExpress },
  tagEslint: { label: 'Eslint', icon: SiEslint },
  tagDocker: { label: 'Docker', icon: BiLogoDocker },
  tagMongoose: { label: 'Mongoose', icon: SiMongoose },
  tagMongodb: { label: 'MongoDB', icon: BiLogoMongodb },
  tagNest: { label: 'Nest.js', icon: SiNestjs },
  tagTypeORM: { label: 'TypeORM' },
  tagPostgreSQL: { label: 'PostgreSQL', icon: BiLogoPostgresql },
  tagSequelize: { label: 'Sequelize', icon: SiSequelize },
  tagWebpack: { label: 'Webpack', icon: SiWebpack },
  tagJest: { label: 'Jest', icon: SiJest },
  tagCypress: { label: 'Cypress', icon: SiCypress },
  tagAxios: { label: 'Axios', icon: SiAxios },
  tagBem: { label: 'BEM', icon: SiBem },
  tagRtk: { label: 'RTK' },
  tagTailwind: { label: 'Tailwind', icon: SiTailwindcss },
  tagHTML: { label: 'HTML', icon: BiLogoHtml5 },
  tagCSS: { label: 'CSS', icon: BiLogoCss3 },
  tagAntdesign: { label: 'Ant design', icon: SiAntdesign },
  tagMocha: { label: 'Mocha', icon: SiMocha },
  tagReactD3: { label: 'React-d3-tree' },
  tagReactDnd: { label: 'React-dnd' },
  tagRecharts: { label: 'Recharts' },
  tagCanvas: { label: 'Canvas' },
  tagForge: { label: 'Forge' },
  tagSvg: { label: 'SVG', icon: SiSvg },
  tagHandlebars: { label: 'Handlebars', icon: SiHandlebarsdotjs },
  tagWebSocket: { label: 'WebSocket' },
  tagServiceWorker: { label: 'ServiceWorker' },
  tagCicd: { label: 'CI/CD' },
  tagFramerMotion: { label: 'Framer-motion' },
  tagSharp: { label: 'Sharp', icon: SiSharp },
};
