import {
  BiLogoJavascript,
  BiLogoTypescript,
  BiLogoReact,
  BiLogoVuejs,
  BiLogoRedux,
  BiLogoMongodb,
  BiLogoPostgresql,
  BiLogoDocker,
  BiLogoGithub,
  BiLogoGitlab,
  BiLogoFigma,
  BiLogoGraphql,
} from 'react-icons/bi';
import {
  SiExpress,
  SiNextdotjs,
  SiNestjs,
  SiJest,
  SiCypress,
  SiMui,
  SiEslint,
  SiPostcss,
  SiWebpack,
  SiSwagger,
  SiSequelize,
  SiMongoose,
  SiAxios,
  SiTailwindcss,
  SiBem,
  SiAntdesign,
  SiPassport,
} from 'react-icons/si';

const techList = [
  { label: 'JavaScript', icon: BiLogoJavascript },
  { label: 'TypeScript', icon: BiLogoTypescript },
  { label: 'React.js', icon: BiLogoReact },
  { label: 'Vue.js', icon: BiLogoVuejs },
  { label: 'Next.js', icon: SiNextdotjs },
  { label: 'Nest.js', icon: SiNestjs },
  { label: 'Express.js', icon: SiExpress },
  { label: 'Redux', icon: BiLogoRedux },
  { label: 'Cypress', icon: SiCypress },
  { label: 'Jest', icon: SiJest },
  { label: 'Webpack', icon: SiWebpack },
  { label: 'PostCSS', icon: SiPostcss },
  { label: 'Eslint', icon: SiEslint },
  { label: 'MUI', icon: SiMui },
  { label: 'Ant design', icon: SiAntdesign },
  { label: 'Tailwind', icon: SiTailwindcss },
  { label: 'BEM', icon: SiBem },
  { label: 'Passport', icon: SiPassport },
  { label: 'MongoDB', icon: BiLogoMongodb },
  { label: 'PostgreSQL', icon: BiLogoPostgresql },
  { label: 'GitHub', icon: BiLogoGithub },
  { label: 'GitLab', icon: BiLogoGitlab },
  { label: 'Docker', icon: BiLogoDocker },
  { label: 'Axios', icon: SiAxios },
  { label: 'GraphQL', icon: BiLogoGraphql },
  { label: 'Figma', icon: BiLogoFigma },
  { label: 'Sequelize', icon: SiSequelize },
  { label: 'Mongoose', icon: SiMongoose },
  { label: 'Swagger', icon: SiSwagger },
];

export default techList;
